### ISSUE TITLE
Web-camera is not supported.

### ISSUE THREAD

**Issue by yurket** [iizukanao/picam#13]
Hi there!
I've tried to run picam with a web-camera I've got some time ago and it doesn't work. It's on you, to decide which cameras to support, but if you're interested, I attach some logs. And I will be glad to provide any information you'll need.

Logs:
https://www.dropbox.com/sh/vphah3s0v93bae1/AACdJ0LuV-73Nz3mKg0g6j0oa?dl=0

`

**Comment by iizukanao** [comment]
Thanks, but I have no plans to support USB webcams in picam. There is a way to do it, but it may not give you good results due to Raspberry Pi's poor USB stack. [Raspberry Pi Camera Module](http://www.raspberrypi.org/products/camera-module/) produces much better results than USB webcams, so I'm not interested in using USB webcams. I strongly recommend you buy Camera Module.
